// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ5LNXurkab29IVAeAo06_hiOY1abMxf8',
    appId: '1:62041396747:web:b82e49a1a8f47a13c4590e',
    messagingSenderId: '62041396747',
    projectId: 'bigfoot-8b82d',
    authDomain: 'bigfoot-8b82d.firebaseapp.com',
    storageBucket: 'bigfoot-8b82d.firebasestorage.app',
    measurementId: 'G-E1Q7ZSRM02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5geH7mrimQbpowGXBmtHBhu84oZPwfbM',
    appId: '1:62041396747:android:312a7e2163c2f934c4590e',
    messagingSenderId: '62041396747',
    projectId: 'bigfoot-8b82d',
    storageBucket: 'bigfoot-8b82d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPMGvbu1l5pBfY9eNONj1fxKT6Lai3Mqw',
    appId: '1:62041396747:ios:449ee3ad1cff56e8c4590e',
    messagingSenderId: '62041396747',
    projectId: 'bigfoot-8b82d',
    storageBucket: 'bigfoot-8b82d.firebasestorage.app',
    iosBundleId: 'com.example.bigfoot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPMGvbu1l5pBfY9eNONj1fxKT6Lai3Mqw',
    appId: '1:62041396747:ios:449ee3ad1cff56e8c4590e',
    messagingSenderId: '62041396747',
    projectId: 'bigfoot-8b82d',
    storageBucket: 'bigfoot-8b82d.firebasestorage.app',
    iosBundleId: 'com.example.bigfoot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ5LNXurkab29IVAeAo06_hiOY1abMxf8',
    appId: '1:62041396747:web:7ef21a6066b66966c4590e',
    messagingSenderId: '62041396747',
    projectId: 'bigfoot-8b82d',
    authDomain: 'bigfoot-8b82d.firebaseapp.com',
    storageBucket: 'bigfoot-8b82d.firebasestorage.app',
    measurementId: 'G-M0Q3YQ5QMG',
  );
}
